<a href="https://colab.research.google.com/github/Danny-Dasilva/Lego_Gen/blob/main/Notebooks/BSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install plotly colour

In [ ]:

# print(random.choice(hex_colors_only))
from colour import Color
red = Color("red")
colors = list(red.range_to(Color("green"),10))

'#f13600'

In [ ]:
data = [[{'x': -1.0, 'y': 1.0, 'z': -1.0}, {'x': -1.0792500972747803, 'y': 0.5590584874153137, 'z': -0.3550416827201843}, {'x': 0.920749843120575, 'y': 0.5590584874153137, 'z': -0.3550416827201843}, {'x': 1.0, 'y': 1.0, 'z': -1.0}], [{'x': -1.0, 'y': 1.0, 'z': -1.0}, {'x': 1.0, 'y': 1.0, 'z': -1.0}, {'x': 1.0, 'y': -1.0, 'z': -1.0}, {'x': -1.0, 'y': -1.0, 'z': -1.0}], [{'x': -1.0, 'y': 1.0, 'z': -1.0}, {'x': -1.0, 'y': -1.0, 'z': -1.0}, {'x': -1.3331773281097412, 'y': -0.08392786979675293, 'z': -0.6690405011177063}, {'x': -1.3331773281097412, 'y': 1.916072130203247, 'z': -0.6690405011177063}], [{'x': -1.0, 'y': 1.0, 'z': -1.0}, {'x': -1.3331773281097412, 'y': 1.916072130203247, 'z': -0.6690405011177063}, {'x': -0.9117384552955627, 'y': 2.0063154697418213, 'z': -0.40377360582351685}, {'x': -0.5785611271858215, 'y': 1.0902433395385742, 'z': -0.7347331047058105}], [{'x': -1.0, 'y': 1.0, 'z': -1.0}, {'x': -0.5785611271858215, 'y': 1.0902433395385742, 'z': -0.7347331047058105}, {'x': -0.3004327118396759, 'y': 1.1598037481307983, 'z': -0.23930585384368896}, {'x': -0.7218716144561768, 'y': 1.0695604085922241, 'z': -0.5045727491378784}]]


In [ ]:
import plotly.graph_objects as go
import numpy as np

colors = ["#ff3333", "#ff336b", "#ff33a8", "#b533ff", "#7a33ff", "#3f33ff", "#3390ff"]
polys = []
# Download data set from plotly repo
for count,polygon in enumerate(data):
    empty = None
    for points in polygon:
        
        r = list(points.values())
        f = np.array([r])
        # empty.append(f)
        if empty is None:
            empty = f
        else:
            empty = np.append(empty,f, axis=0)
    
    x, y, z = empty.T
    
    polys.append(go.Mesh3d(x=x, y=y, z=z, color=colors[count], opacity=0.8))
    
fig = go.Figure(data=polys)
fig.show()

#Example call

In [ ]:

polys  = []
# Download data set from plotly repo
for polygon in data:
    empty = None
    for points in polygon:
   
        r = list(points.values())
        f = np.array([r])
     
        if empty is None:
            empty = f
        else:
            empty = np.append(empty,f, axis=0)
   
    polys.append(empty * 1)

vertices = np.concatenate(polys, axis=0)
face_idxs = np.concatenate([np.ones(poly.shape[0]) * i for i, poly in enumerate(polys)], axis=0)

In [ ]:
vertices

array([[-1.        ,  1.        , -1.        ],
       [-1.0792501 ,  0.55905849, -0.35504168],
       [ 0.92074984,  0.55905849, -0.35504168],
       [ 1.        ,  1.        , -1.        ],
       [-1.        ,  1.        , -1.        ],
       [ 1.        ,  1.        , -1.        ],
       [ 1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        ],
       [-1.        ,  1.        , -1.        ],
       [-1.        , -1.        , -1.        ],
       [-1.33317733, -0.08392787, -0.6690405 ],
       [-1.33317733,  1.91607213, -0.6690405 ],
       [-1.        ,  1.        , -1.        ],
       [-1.33317733,  1.91607213, -0.6690405 ],
       [-0.91173846,  2.00631547, -0.40377361],
       [-0.57856113,  1.09024334, -0.7347331 ],
       [-1.        ,  1.        , -1.        ],
       [-0.57856113,  1.09024334, -0.7347331 ],
       [-0.30043271,  1.15980375, -0.23930585],
       [-0.72187161,  1.06956041, -0.50457275]])

In [ ]:
face_idxs

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4.])

In [ ]:
_, idx = np.unique(face_idxs, return_index=True)
polygon_count = face_idxs[np.sort(idx)].astype(int).tolist()
sort_order = polygon_count

In [ ]:
polygon = vertices[face_idxs==0]
polygon

array([[-1.        ,  1.        , -1.        ],
       [-1.0792501 ,  0.55905849, -0.35504168],
       [ 0.92074984,  0.55905849, -0.35504168],
       [ 1.        ,  1.        , -1.        ]])

In [ ]:
# polygon = vertices[face_idxs==node]
# normal = np.cross(random vector - normalized , polygon[1] - polygon[0])
normal = np.cross(polygon[2] - polygon[0], polygon[1] - polygon[0])
p = polygon[0]

positive = []
negative = []
other = []
for i in sort_order:
  polygon = vertices[face_idxs==i]
  
  dot = np.around(np.dot(p-polygon, normal), 10)
  if (np.all(dot >= 0)):
    positive.append(i)
  elif (np.all(dot <= 0)):
    negative.append(i)
  else:
    other.append(i)

print(positive,negative,other)
  
    # positive or zero
    # negative or zero
    # some points are positive or negative



[0, 1] [3, 4] [2]


In [ ]:
polygon = vertices[face_idxs==other[0]]
dot = np.around(np.dot(p-polygon, normal), 10)

In [ ]:
dot

array([ 0.        ,  0.27002808,  0.13899267, -0.13103542])

In [ ]:
edges = []
for i in (polygon[dot < 0]):
  for j in (polygon[dot > 0]):
    edges.append(np.array([i,j]))

In [ ]:
edge = edges[0]
newpoint = edge[0]+(np.dot(edge[0]-p,normal)/np.dot(edge[0]-edge[1],normal)*(edge[1]-edge[0]))

In [ ]:
products = 453
pages = products//250
pages


1

In [ ]:
import math
math.ceil(products/250)

2